# Generated by Django 6.0.1 on 2026-01-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], max_length=1, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('highestQualification', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('nielitStudent', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('trainingCenter', models.CharField(blank=True, choices=[('I', 'Inderlok'), ('J', 'janakpuri'), ('K', 'Karakrdooma')], max_length=1, null=True)),
                ('passingYear', models.CharField(blank=True, max_length=4, null=True)),
                ('skills', models.CharField(blank=True, choices=[('S&SE', 'Software & Systems Expert (O Level/A Level/Programming/Web Development)'), ('AI&ML', 'AI & Data Science(AI,ML,Data Science)'), ('DM', 'Digital Media (Multimedia Tools,Digital Marketing)'), ('AC', 'Accounting'), ('GN', 'General Office Automation'), ('O', 'Other')], max_length=100, null=True)),
                ('employed', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('experience', models.CharField(blank=True, max_length=10, null=True)),
                ('dec', models.CharField(blank=True, choices=[('Declared', 'I am aware that information provided bt me in this form shall be shared by NIELIT with prospective companies,if required.')], max_length=10, null=True)),
            ],
        ),
    ]
