# Generated by Django 6.0.1 on 2026-01-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_m',
            name='trainingCenter',
        ),
    ]
