# Generated by Django 6.0.1 on 2026-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0002_remove_form_m_trainingcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_m',
            name='skills',
            field=models.CharField(choices=[('S&SE', 'Software & Systems Expert (O Level/A Level/Programming/Web Development)'), ('AI&ML', 'AI & Data Science(AI,ML,Data Science)'), ('DM', 'Digital Media (Multimedia Tools,Digital Marketing)'), ('AC', 'Accounting'), ('GN', 'General Office Automation'), ('O', 'Other')], max_length=100, null=True),
        ),
    ]
