# Generated by Django 6.0.1 on 2026-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0003_alter_form_m_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_m',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_m',
            name='trainingCenter',
            field=models.CharField(blank=True, choices=[('I', 'Inderlok'), ('J', 'janakpuri'), ('K', 'Karakrdooma')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='form_m',
            name='skills',
            field=models.CharField(blank=True, choices=[('S&SE', 'Software & Systems Expert (O Level/A Level/Programming/Web Development)'), ('AI&ML', 'AI & Data Science(AI,ML,Data Science)'), ('DM', 'Digital Media (Multimedia Tools,Digital Marketing)'), ('AC', 'Accounting'), ('GN', 'General Office Automation'), ('O', 'Other')], max_length=100, null=True),
        ),
    ]
