# Generated by Django 6.0.1 on 2026-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0006_alter_form_m_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_m',
            name='skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
