# Generated by Django 5.2.8 on 2026-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0009_alter_form_m_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_m',
            name='dec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form_m',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'other'), ('M', 'Male')], max_length=1),
        ),
        migrations.AlterField(
            model_name='form_m',
            name='highestQualification',
            field=models.CharField(choices=[('10+2', '10+2 / ITI / Pursuing Graduation'), ('UG', 'Graduation (B.Sc / B.Com / BA / BBA)'), ('TECH', 'Technical (CS / IT / BCA / B.Tech)'), ('PG', 'Post Graduate'), ('MTECH', 'MCA / M.Tech'), ('O', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='form_m',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form_m',
            name='trainingCenter',
            field=models.CharField(blank=True, choices=[('J', 'Janakpuri'), ('I', 'Inderlok'), ('K', 'Karkardooma')], max_length=1, null=True),
        ),
    ]
