# Generated by Django 5.2.8 on 2026-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0011_alter_form_m_gender_alter_form_m_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_m',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='form_m',
            name='trainingCenter',
            field=models.CharField(blank=True, choices=[('K', 'Karkardooma'), ('J', 'Janakpuri'), ('I', 'Inderlok')], max_length=1, null=True),
        ),
    ]
