# Generated by Django 5.2.8 on 2026-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_fair', '0012_alter_form_m_gender_alter_form_m_trainingcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_m',
            name='trainingCenter',
            field=models.CharField(blank=True, choices=[('K', 'Karkardooma'), ('I', 'Inderlok'), ('J', 'Janakpuri')], max_length=1, null=True),
        ),
    ]
